import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React from "react";
import ThemeContext from "@/app/context/ThemeContext";
import Appbar from "@/app/Components/Appbar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ThemeContext>
            <Appbar />
            {children}
        </ThemeContext>
        </body>
        </html>
    )
}
